[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
utc-dt = "0.3.1"
rusqlite = "0.35.0"
winit = "0.30.10"
wgpu = "25.0.0"
egui = "0.31.1"
egui-winit = "0.31.1"
egui-wgpu = "0.31.1"
pollster = "0.4.0"
colored = "3.0.0"
